### PR TITLE
fix: Fixing executed proposal order

### LINKED ISSUE #429: Ordering issue on new schemes
It seems ordering is again broken.

New scheme proposals are being sorted upside down on executed proposals. Most easily seen on xdai where there is a mix of old and new schemes. Old schemes are fine but new ones are upside down and difficult to find without filtering. 

Screenshot 2021-11-26 at 11 35 09

### PR DESCRIPTION
**Pull request by rossneilson**
This was fixes previously but I think was removed when migrating to a hook.
Also removing old unused code

Closes #429

### CODE REVIEW

File: src/hooks/useFilterCriteria.ts [hunk 1]
```diff
@@ -19,6 +18,12 @@ interface useFilterCriteriaReturns {
   loading: boolean;
 }
 
+export const orderByNewestTimeToFinish = (a: any, b: any) =>
```
Comment (MiltonTulli) [inline src/hooks/useFilterCriteria.ts]: Not sure if the intention is not to use a lot of types. But `(a: ProposalsExtended, b: ProposalsExtended)` sounds appropriate. ( for both `orderByNewestTimeToFinish` and `orderByOldestTimeToFinish` )

**Review by MiltonTulli — DISMISSED** [review]

File: src/hooks/useFilterCriteria.ts (hunk 1 above)
Comment (rossneilson) [reply src/hooks/useFilterCriteria.ts]: Nice spot, I was just copy pasting. Fixed now

**Review by MiltonTulli — APPROVED** [review]
